# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/user/application_security/secret_detection/pipeline/configure
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

#include:
#- template: Auto-DevOps.gitlab-ci.yml

stages:
- lint
- quality
- build
- test
#- deploy
#- review
#- dast
#- staging
#- canary
#- production
#- incremental rollout 10%
#- incremental rollout 25%
#- incremental rollout 50%
#- incremental rollout 100%
#- performance
#- cleanup

run_frontend_lint:
  stage: lint
  tags:
    - docker
  image: node:20-alpine
  script:
    - cd frontend 
    - npm install
    - npm run lint

run_backend_lint:
  stage: lint
  tags:
    - docker
  image: python:3.11-slim
  script:
    - cd backend 
    - python -m pip install --no-cache-dir -r requirements.txt
    - python test_app.py


code_quality:
  stage: quality
  tags:
    - docker
  image: python:3.11-slim
  before_script:
    - python -m pip install --no-cache-dir black isort
  script:
    - cd backend
    - isort --check-only .
    - black --check .
  allow_failure: true

#sast:
#  stage: test

